Imports MySql.Data.MySqlClient
Module Modulo_Conexion
    Friend Conexion As New MySqlConnection
    Friend SC As New MySqlCommand
    Friend DA As New MySqlDataAdapter
    Friend DS As New DataSet()
    Friend DT As New DataTable
    Friend SC2 As New MySqlCommand
    Friend DA2 As New MySqlDataAdapter
    Friend DS2 As New DataSet()
    Friend DT2 As New DataTable
    Friend SC3 As New MySqlCommand
    Friend DA3 As New MySqlDataAdapter
    Friend DS3 As New DataSet()
    Friend DT3 As New DataTable
    Friend SC4 As New MySqlCommand
    Friend DA4 As New MySqlDataAdapter
    Friend DS4 As New DataSet()
    Friend DT4 As New DataTable
    Friend SC5 As New MySqlCommand
    Friend DA5 As New MySqlDataAdapter
    Friend DS5 As New DataSet()
    Friend DT5 As New DataTable
    Friend SC7 As New MySqlCommand
    Friend DA7 As New MySqlDataAdapter
    Friend DS7 As New DataSet()
    Friend DT7 As New DataTable
    Friend SC8 As New MySqlCommand
    Friend DA8 As New MySqlDataAdapter
    Friend DS8 As New DataSet()
    Friend DT8 As New DataTable
    Friend SC9 As New MySqlCommand
    Friend DA9 As New MySqlDataAdapter
    Friend DS9 As New DataSet()
    Friend DT9 As New DataTable
    Friend SC01 As New MySqlCommand
    Friend DA01 As New MySqlDataAdapter
    Friend DS01 As New DataSet()
    Friend DT01 As New DataTable
    Friend SC02 As New MySqlCommand
    Friend DA02 As New MySqlDataAdapter
    Friend DS02 As New DataSet()
    Friend DT02 As New DataTable
    Friend SC03 As New MySqlCommand
    Friend DA03 As New MySqlDataAdapter
    Friend DS03 As New DataSet()
    Friend DT03 As New DataTable
    Friend SC04 As New MySqlCommand
    Friend DA04 As New MySqlDataAdapter
    Friend DS04 As New DataSet()
    Friend DT04 As New DataTable
    Friend SC05 As New MySqlCommand
    Friend DA05 As New MySqlDataAdapter
    Friend DS05 As New DataSet()
    Friend DT05 As New DataTable
    Friend SC06 As New MySqlCommand
    Friend DA06 As New MySqlDataAdapter
    Friend DS06 As New DataSet()
    Friend DT06 As New DataTable
    Friend SC07 As New MySqlCommand
    Friend DA07 As New MySqlDataAdapter
    Friend DS07 As New DataSet()
    Friend DT07 As New DataTable
    Friend SC08 As New MySqlCommand
    Friend DA08 As New MySqlDataAdapter
    Friend DS08 As New DataSet()
    Friend DT08 As New DataTable
    Friend SC09 As New MySqlCommand
    Friend DA09 As New MySqlDataAdapter
    Friend DS09 As New DataSet()
    Friend DT09 As New DataTable
    Friend SC10 As New MySqlCommand
    Friend DA10 As New MySqlDataAdapter
    Friend DS10 As New DataSet()
    Friend DT10 As New DataTable
    Friend SC11 As New MySqlCommand
    Friend DA11 As New MySqlDataAdapter
    Friend DS11 As New DataSet()
    Friend DT11 As New DataTable
    Friend SC12 As New MySqlCommand
    Friend DA12 As New MySqlDataAdapter
    Friend DS12 As New DataSet()
    Friend DT12 As New DataTable
    Friend SC13 As New MySqlCommand
    Friend DA13 As New MySqlDataAdapter
    Friend DS13 As New DataSet()
    Friend DT13 As New DataTable
    Friend SC14 As New MySqlCommand
    Friend DA14 As New MySqlDataAdapter
    Friend DS14 As New DataSet()
    Friend DT14 As New DataTable
End Module
