//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SATModel", "FK__RepuestoO__idOrd__2FCF1A8A", "OrdenTrabajo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.OrdenTrabajo), "RepuestoOrden", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.RepuestoOrden))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SATModel", "FK__Servicios__idOrd__19DFD96B", "OrdenTrabajo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.OrdenTrabajo), "ServiciosOrden", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.ServiciosOrden))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SATModel", "FK__PrecioRep__idPre__3CF40B7E", "Precio", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.Precio), "PrecioRepuesto", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.PrecioRepuesto))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SATModel", "FK__PrecioSer__idPre__308E3499", "Precio", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.Precio), "PrecioServicio", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.PrecioServicio))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SATModel", "FK__PrecioRep__idRep__3DE82FB7", "Repuesto", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.Repuesto), "PrecioRepuesto", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.PrecioRepuesto))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SATModel", "FK__RepuestoO__idPre__3EDC53F0", "PrecioRepuesto", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.PrecioRepuesto), "RepuestoOrden", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.RepuestoOrden))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SATModel", "FK__PrecioSer__idSer__318258D2", "Servicio", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.Servicio), "PrecioServicio", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.PrecioServicio))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SATModel", "FK__Servicios__idPre__336AA144", "PrecioServicio", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.PrecioServicio), "ServiciosOrden", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.ServiciosOrden))]

// Nombre de archivo original:
// Fecha de generación: 09/03/2012 19:25:08
namespace WebApplication1
{
    
    /// <summary>
    /// No hay ningún comentario para SATEntities1 en el esquema.
    /// </summary>
    public partial class SATEntities1 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto SATEntities1 usando la cadena de conexión encontrada en la sección 'SATEntities1' del archivo de configuración de la aplicación.
        /// </summary>
        public SATEntities1() : 
                base("name=SATEntities1", "SATEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto SATEntities1.
        /// </summary>
        public SATEntities1(string connectionString) : 
                base(connectionString, "SATEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto SATEntities1.
        /// </summary>
        public SATEntities1(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SATEntities1")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para OrdenTrabajo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<OrdenTrabajo> OrdenTrabajo
        {
            get
            {
                if ((this._OrdenTrabajo == null))
                {
                    this._OrdenTrabajo = base.CreateQuery<OrdenTrabajo>("[OrdenTrabajo]");
                }
                return this._OrdenTrabajo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<OrdenTrabajo> _OrdenTrabajo;
        /// <summary>
        /// No hay ningún comentario para Precio en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Precio> Precio
        {
            get
            {
                if ((this._Precio == null))
                {
                    this._Precio = base.CreateQuery<Precio>("[Precio]");
                }
                return this._Precio;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Precio> _Precio;
        /// <summary>
        /// No hay ningún comentario para PrecioRepuesto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<PrecioRepuesto> PrecioRepuesto
        {
            get
            {
                if ((this._PrecioRepuesto == null))
                {
                    this._PrecioRepuesto = base.CreateQuery<PrecioRepuesto>("[PrecioRepuesto]");
                }
                return this._PrecioRepuesto;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<PrecioRepuesto> _PrecioRepuesto;
        /// <summary>
        /// No hay ningún comentario para PrecioServicio en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<PrecioServicio> PrecioServicio
        {
            get
            {
                if ((this._PrecioServicio == null))
                {
                    this._PrecioServicio = base.CreateQuery<PrecioServicio>("[PrecioServicio]");
                }
                return this._PrecioServicio;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<PrecioServicio> _PrecioServicio;
        /// <summary>
        /// No hay ningún comentario para Repuesto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Repuesto> Repuesto
        {
            get
            {
                if ((this._Repuesto == null))
                {
                    this._Repuesto = base.CreateQuery<Repuesto>("[Repuesto]");
                }
                return this._Repuesto;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Repuesto> _Repuesto;
        /// <summary>
        /// No hay ningún comentario para RepuestoOrden en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<RepuestoOrden> RepuestoOrden
        {
            get
            {
                if ((this._RepuestoOrden == null))
                {
                    this._RepuestoOrden = base.CreateQuery<RepuestoOrden>("[RepuestoOrden]");
                }
                return this._RepuestoOrden;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<RepuestoOrden> _RepuestoOrden;
        /// <summary>
        /// No hay ningún comentario para Servicio en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Servicio> Servicio
        {
            get
            {
                if ((this._Servicio == null))
                {
                    this._Servicio = base.CreateQuery<Servicio>("[Servicio]");
                }
                return this._Servicio;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Servicio> _Servicio;
        /// <summary>
        /// No hay ningún comentario para ServiciosOrden en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ServiciosOrden> ServiciosOrden
        {
            get
            {
                if ((this._ServiciosOrden == null))
                {
                    this._ServiciosOrden = base.CreateQuery<ServiciosOrden>("[ServiciosOrden]");
                }
                return this._ServiciosOrden;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ServiciosOrden> _ServiciosOrden;
        /// <summary>
        /// No hay ningún comentario para OrdenTrabajo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToOrdenTrabajo(OrdenTrabajo ordenTrabajo)
        {
            base.AddObject("OrdenTrabajo", ordenTrabajo);
        }
        /// <summary>
        /// No hay ningún comentario para Precio en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPrecio(Precio precio)
        {
            base.AddObject("Precio", precio);
        }
        /// <summary>
        /// No hay ningún comentario para PrecioRepuesto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPrecioRepuesto(PrecioRepuesto precioRepuesto)
        {
            base.AddObject("PrecioRepuesto", precioRepuesto);
        }
        /// <summary>
        /// No hay ningún comentario para PrecioServicio en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPrecioServicio(PrecioServicio precioServicio)
        {
            base.AddObject("PrecioServicio", precioServicio);
        }
        /// <summary>
        /// No hay ningún comentario para Repuesto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToRepuesto(Repuesto repuesto)
        {
            base.AddObject("Repuesto", repuesto);
        }
        /// <summary>
        /// No hay ningún comentario para RepuestoOrden en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToRepuestoOrden(RepuestoOrden repuestoOrden)
        {
            base.AddObject("RepuestoOrden", repuestoOrden);
        }
        /// <summary>
        /// No hay ningún comentario para Servicio en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToServicio(Servicio servicio)
        {
            base.AddObject("Servicio", servicio);
        }
        /// <summary>
        /// No hay ningún comentario para ServiciosOrden en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToServiciosOrden(ServiciosOrden serviciosOrden)
        {
            base.AddObject("ServiciosOrden", serviciosOrden);
        }
    }
    /// <summary>
    /// No hay ningún comentario para SATModel.OrdenTrabajo en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// idOrdenTrabajo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SATModel", Name="OrdenTrabajo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class OrdenTrabajo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto OrdenTrabajo.
        /// </summary>
        /// <param name="idOrdenTrabajo">Valor inicial de idOrdenTrabajo.</param>
        /// <param name="estadoOrdenTrabajo">Valor inicial de estadoOrdenTrabajo.</param>
        /// <param name="idUsuario">Valor inicial de idUsuario.</param>
        /// <param name="idGarantia">Valor inicial de idGarantia.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static OrdenTrabajo CreateOrdenTrabajo(long idOrdenTrabajo, byte estadoOrdenTrabajo, long idUsuario, long idGarantia)
        {
            OrdenTrabajo ordenTrabajo = new OrdenTrabajo();
            ordenTrabajo.idOrdenTrabajo = idOrdenTrabajo;
            ordenTrabajo.estadoOrdenTrabajo = estadoOrdenTrabajo;
            ordenTrabajo.idUsuario = idUsuario;
            ordenTrabajo.idGarantia = idGarantia;
            return ordenTrabajo;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad idOrdenTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idOrdenTrabajo
        {
            get
            {
                return this._idOrdenTrabajo;
            }
            set
            {
                this.OnidOrdenTrabajoChanging(value);
                this.ReportPropertyChanging("idOrdenTrabajo");
                this._idOrdenTrabajo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idOrdenTrabajo");
                this.OnidOrdenTrabajoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idOrdenTrabajo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidOrdenTrabajoChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidOrdenTrabajoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fechaOrdenTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> fechaOrdenTrabajo
        {
            get
            {
                return this._fechaOrdenTrabajo;
            }
            set
            {
                this.OnfechaOrdenTrabajoChanging(value);
                this.ReportPropertyChanging("fechaOrdenTrabajo");
                this._fechaOrdenTrabajo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fechaOrdenTrabajo");
                this.OnfechaOrdenTrabajoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _fechaOrdenTrabajo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaOrdenTrabajoChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaOrdenTrabajoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad estadoOrdenTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte estadoOrdenTrabajo
        {
            get
            {
                return this._estadoOrdenTrabajo;
            }
            set
            {
                this.OnestadoOrdenTrabajoChanging(value);
                this.ReportPropertyChanging("estadoOrdenTrabajo");
                this._estadoOrdenTrabajo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("estadoOrdenTrabajo");
                this.OnestadoOrdenTrabajoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte _estadoOrdenTrabajo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnestadoOrdenTrabajoChanging(byte value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnestadoOrdenTrabajoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad descOrdenTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string descOrdenTrabajo
        {
            get
            {
                return this._descOrdenTrabajo;
            }
            set
            {
                this.OndescOrdenTrabajoChanging(value);
                this.ReportPropertyChanging("descOrdenTrabajo");
                this._descOrdenTrabajo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("descOrdenTrabajo");
                this.OndescOrdenTrabajoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _descOrdenTrabajo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescOrdenTrabajoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescOrdenTrabajoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad iConcurrenciaOrdenTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> iConcurrenciaOrdenTrabajo
        {
            get
            {
                return this._iConcurrenciaOrdenTrabajo;
            }
            set
            {
                this.OniConcurrenciaOrdenTrabajoChanging(value);
                this.ReportPropertyChanging("iConcurrenciaOrdenTrabajo");
                this._iConcurrenciaOrdenTrabajo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("iConcurrenciaOrdenTrabajo");
                this.OniConcurrenciaOrdenTrabajoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _iConcurrenciaOrdenTrabajo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaOrdenTrabajoChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaOrdenTrabajoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad idUsuario en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idUsuario
        {
            get
            {
                return this._idUsuario;
            }
            set
            {
                this.OnidUsuarioChanging(value);
                this.ReportPropertyChanging("idUsuario");
                this._idUsuario = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idUsuario");
                this.OnidUsuarioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idUsuario;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidUsuarioChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidUsuarioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad idGarantia en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idGarantia
        {
            get
            {
                return this._idGarantia;
            }
            set
            {
                this.OnidGarantiaChanging(value);
                this.ReportPropertyChanging("idGarantia");
                this._idGarantia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idGarantia");
                this.OnidGarantiaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idGarantia;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidGarantiaChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidGarantiaChanged();
        /// <summary>
        /// No hay ningún comentario para RepuestoOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__RepuestoO__idOrd__2FCF1A8A", "RepuestoOrden")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<RepuestoOrden> RepuestoOrden
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<RepuestoOrden>("SATModel.FK__RepuestoO__idOrd__2FCF1A8A", "RepuestoOrden");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<RepuestoOrden>("SATModel.FK__RepuestoO__idOrd__2FCF1A8A", "RepuestoOrden", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para ServiciosOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__Servicios__idOrd__19DFD96B", "ServiciosOrden")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ServiciosOrden> ServiciosOrden
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ServiciosOrden>("SATModel.FK__Servicios__idOrd__19DFD96B", "ServiciosOrden");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ServiciosOrden>("SATModel.FK__Servicios__idOrd__19DFD96B", "ServiciosOrden", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para SATModel.Precio en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// idPrecio
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SATModel", Name="Precio")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Precio : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Precio.
        /// </summary>
        /// <param name="idPrecio">Valor inicial de idPrecio.</param>
        /// <param name="montoPrecio">Valor inicial de montoPrecio.</param>
        /// <param name="fechaPrecio">Valor inicial de fechaPrecio.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Precio CreatePrecio(int idPrecio, double montoPrecio, global::System.DateTime fechaPrecio)
        {
            Precio precio = new Precio();
            precio.idPrecio = idPrecio;
            precio.montoPrecio = montoPrecio;
            precio.fechaPrecio = fechaPrecio;
            return precio;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad idPrecio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idPrecio
        {
            get
            {
                return this._idPrecio;
            }
            set
            {
                this.OnidPrecioChanging(value);
                this.ReportPropertyChanging("idPrecio");
                this._idPrecio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idPrecio");
                this.OnidPrecioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idPrecio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidPrecioChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidPrecioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad montoPrecio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public double montoPrecio
        {
            get
            {
                return this._montoPrecio;
            }
            set
            {
                this.OnmontoPrecioChanging(value);
                this.ReportPropertyChanging("montoPrecio");
                this._montoPrecio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("montoPrecio");
                this.OnmontoPrecioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private double _montoPrecio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmontoPrecioChanging(double value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmontoPrecioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fechaPrecio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime fechaPrecio
        {
            get
            {
                return this._fechaPrecio;
            }
            set
            {
                this.OnfechaPrecioChanging(value);
                this.ReportPropertyChanging("fechaPrecio");
                this._fechaPrecio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fechaPrecio");
                this.OnfechaPrecioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _fechaPrecio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaPrecioChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaPrecioChanged();
        /// <summary>
        /// No hay ningún comentario para PrecioRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__PrecioRep__idPre__3CF40B7E", "PrecioRepuesto")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PrecioRepuesto> PrecioRepuesto
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PrecioRepuesto>("SATModel.FK__PrecioRep__idPre__3CF40B7E", "PrecioRepuesto");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PrecioRepuesto>("SATModel.FK__PrecioRep__idPre__3CF40B7E", "PrecioRepuesto", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para PrecioServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__PrecioSer__idPre__308E3499", "PrecioServicio")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PrecioServicio> PrecioServicio
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PrecioServicio>("SATModel.FK__PrecioSer__idPre__308E3499", "PrecioServicio");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PrecioServicio>("SATModel.FK__PrecioSer__idPre__308E3499", "PrecioServicio", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para SATModel.PrecioRepuesto en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// idPrecioRepuesto
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SATModel", Name="PrecioRepuesto")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PrecioRepuesto : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto PrecioRepuesto.
        /// </summary>
        /// <param name="idPrecioRepuesto">Valor inicial de idPrecioRepuesto.</param>
        /// <param name="fechaPrecioRepuesto">Valor inicial de fechaPrecioRepuesto.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static PrecioRepuesto CreatePrecioRepuesto(long idPrecioRepuesto, global::System.DateTime fechaPrecioRepuesto)
        {
            PrecioRepuesto precioRepuesto = new PrecioRepuesto();
            precioRepuesto.idPrecioRepuesto = idPrecioRepuesto;
            precioRepuesto.fechaPrecioRepuesto = fechaPrecioRepuesto;
            return precioRepuesto;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad idPrecioRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idPrecioRepuesto
        {
            get
            {
                return this._idPrecioRepuesto;
            }
            set
            {
                this.OnidPrecioRepuestoChanging(value);
                this.ReportPropertyChanging("idPrecioRepuesto");
                this._idPrecioRepuesto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idPrecioRepuesto");
                this.OnidPrecioRepuestoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idPrecioRepuesto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidPrecioRepuestoChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidPrecioRepuestoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fechaPrecioRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime fechaPrecioRepuesto
        {
            get
            {
                return this._fechaPrecioRepuesto;
            }
            set
            {
                this.OnfechaPrecioRepuestoChanging(value);
                this.ReportPropertyChanging("fechaPrecioRepuesto");
                this._fechaPrecioRepuesto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fechaPrecioRepuesto");
                this.OnfechaPrecioRepuestoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _fechaPrecioRepuesto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaPrecioRepuestoChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaPrecioRepuestoChanged();
        /// <summary>
        /// No hay ningún comentario para Precio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__PrecioRep__idPre__3CF40B7E", "Precio")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Precio Precio
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Precio>("SATModel.FK__PrecioRep__idPre__3CF40B7E", "Precio").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Precio>("SATModel.FK__PrecioRep__idPre__3CF40B7E", "Precio").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Precio en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Precio> PrecioReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Precio>("SATModel.FK__PrecioRep__idPre__3CF40B7E", "Precio");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Precio>("SATModel.FK__PrecioRep__idPre__3CF40B7E", "Precio", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para Repuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__PrecioRep__idRep__3DE82FB7", "Repuesto")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Repuesto Repuesto
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Repuesto>("SATModel.FK__PrecioRep__idRep__3DE82FB7", "Repuesto").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Repuesto>("SATModel.FK__PrecioRep__idRep__3DE82FB7", "Repuesto").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Repuesto en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Repuesto> RepuestoReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Repuesto>("SATModel.FK__PrecioRep__idRep__3DE82FB7", "Repuesto");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Repuesto>("SATModel.FK__PrecioRep__idRep__3DE82FB7", "Repuesto", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para RepuestoOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__RepuestoO__idPre__3EDC53F0", "RepuestoOrden")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<RepuestoOrden> RepuestoOrden
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<RepuestoOrden>("SATModel.FK__RepuestoO__idPre__3EDC53F0", "RepuestoOrden");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<RepuestoOrden>("SATModel.FK__RepuestoO__idPre__3EDC53F0", "RepuestoOrden", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para SATModel.PrecioServicio en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// idPrecioServicio
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SATModel", Name="PrecioServicio")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PrecioServicio : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto PrecioServicio.
        /// </summary>
        /// <param name="idPrecioServicio">Valor inicial de idPrecioServicio.</param>
        /// <param name="fechaPrecioServicio">Valor inicial de fechaPrecioServicio.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static PrecioServicio CreatePrecioServicio(long idPrecioServicio, global::System.DateTime fechaPrecioServicio)
        {
            PrecioServicio precioServicio = new PrecioServicio();
            precioServicio.idPrecioServicio = idPrecioServicio;
            precioServicio.fechaPrecioServicio = fechaPrecioServicio;
            return precioServicio;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad idPrecioServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idPrecioServicio
        {
            get
            {
                return this._idPrecioServicio;
            }
            set
            {
                this.OnidPrecioServicioChanging(value);
                this.ReportPropertyChanging("idPrecioServicio");
                this._idPrecioServicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idPrecioServicio");
                this.OnidPrecioServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idPrecioServicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidPrecioServicioChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidPrecioServicioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fechaPrecioServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime fechaPrecioServicio
        {
            get
            {
                return this._fechaPrecioServicio;
            }
            set
            {
                this.OnfechaPrecioServicioChanging(value);
                this.ReportPropertyChanging("fechaPrecioServicio");
                this._fechaPrecioServicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fechaPrecioServicio");
                this.OnfechaPrecioServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _fechaPrecioServicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaPrecioServicioChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaPrecioServicioChanged();
        /// <summary>
        /// No hay ningún comentario para Precio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__PrecioSer__idPre__308E3499", "Precio")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Precio Precio
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Precio>("SATModel.FK__PrecioSer__idPre__308E3499", "Precio").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Precio>("SATModel.FK__PrecioSer__idPre__308E3499", "Precio").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Precio en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Precio> PrecioReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Precio>("SATModel.FK__PrecioSer__idPre__308E3499", "Precio");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Precio>("SATModel.FK__PrecioSer__idPre__308E3499", "Precio", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para Servicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__PrecioSer__idSer__318258D2", "Servicio")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Servicio Servicio
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Servicio>("SATModel.FK__PrecioSer__idSer__318258D2", "Servicio").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Servicio>("SATModel.FK__PrecioSer__idSer__318258D2", "Servicio").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Servicio en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Servicio> ServicioReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Servicio>("SATModel.FK__PrecioSer__idSer__318258D2", "Servicio");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Servicio>("SATModel.FK__PrecioSer__idSer__318258D2", "Servicio", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para ServiciosOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__Servicios__idPre__336AA144", "ServiciosOrden")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ServiciosOrden> ServiciosOrden
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ServiciosOrden>("SATModel.FK__Servicios__idPre__336AA144", "ServiciosOrden");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ServiciosOrden>("SATModel.FK__Servicios__idPre__336AA144", "ServiciosOrden", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para SATModel.Repuesto en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// idRepuesto
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SATModel", Name="Repuesto")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Repuesto : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Repuesto.
        /// </summary>
        /// <param name="idRepuesto">Valor inicial de idRepuesto.</param>
        /// <param name="descRepuesto">Valor inicial de descRepuesto.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Repuesto CreateRepuesto(long idRepuesto, string descRepuesto)
        {
            Repuesto repuesto = new Repuesto();
            repuesto.idRepuesto = idRepuesto;
            repuesto.descRepuesto = descRepuesto;
            return repuesto;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad idRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idRepuesto
        {
            get
            {
                return this._idRepuesto;
            }
            set
            {
                this.OnidRepuestoChanging(value);
                this.ReportPropertyChanging("idRepuesto");
                this._idRepuesto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idRepuesto");
                this.OnidRepuestoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idRepuesto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidRepuestoChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidRepuestoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad descRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string descRepuesto
        {
            get
            {
                return this._descRepuesto;
            }
            set
            {
                this.OndescRepuestoChanging(value);
                this.ReportPropertyChanging("descRepuesto");
                this._descRepuesto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("descRepuesto");
                this.OndescRepuestoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _descRepuesto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescRepuestoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescRepuestoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad iConcurrenciaRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> iConcurrenciaRepuesto
        {
            get
            {
                return this._iConcurrenciaRepuesto;
            }
            set
            {
                this.OniConcurrenciaRepuestoChanging(value);
                this.ReportPropertyChanging("iConcurrenciaRepuesto");
                this._iConcurrenciaRepuesto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("iConcurrenciaRepuesto");
                this.OniConcurrenciaRepuestoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _iConcurrenciaRepuesto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaRepuestoChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaRepuestoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad idMarca en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<long> idMarca
        {
            get
            {
                return this._idMarca;
            }
            set
            {
                this.OnidMarcaChanging(value);
                this.ReportPropertyChanging("idMarca");
                this._idMarca = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idMarca");
                this.OnidMarcaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<long> _idMarca;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidMarcaChanging(global::System.Nullable<long> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidMarcaChanged();
        /// <summary>
        /// No hay ningún comentario para PrecioRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__PrecioRep__idRep__3DE82FB7", "PrecioRepuesto")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PrecioRepuesto> PrecioRepuesto
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PrecioRepuesto>("SATModel.FK__PrecioRep__idRep__3DE82FB7", "PrecioRepuesto");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PrecioRepuesto>("SATModel.FK__PrecioRep__idRep__3DE82FB7", "PrecioRepuesto", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para SATModel.RepuestoOrden en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// idRepuestoOrden
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SATModel", Name="RepuestoOrden")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class RepuestoOrden : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto RepuestoOrden.
        /// </summary>
        /// <param name="idRepuestoOrden">Valor inicial de idRepuestoOrden.</param>
        /// <param name="cantidadRepuestoOrden">Valor inicial de cantidadRepuestoOrden.</param>
        /// <param name="fechaRepuesto">Valor inicial de fechaRepuesto.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static RepuestoOrden CreateRepuestoOrden(long idRepuestoOrden, int cantidadRepuestoOrden, global::System.DateTime fechaRepuesto)
        {
            RepuestoOrden repuestoOrden = new RepuestoOrden();
            repuestoOrden.idRepuestoOrden = idRepuestoOrden;
            repuestoOrden.cantidadRepuestoOrden = cantidadRepuestoOrden;
            repuestoOrden.fechaRepuesto = fechaRepuesto;
            return repuestoOrden;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad idRepuestoOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idRepuestoOrden
        {
            get
            {
                return this._idRepuestoOrden;
            }
            set
            {
                this.OnidRepuestoOrdenChanging(value);
                this.ReportPropertyChanging("idRepuestoOrden");
                this._idRepuestoOrden = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idRepuestoOrden");
                this.OnidRepuestoOrdenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idRepuestoOrden;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidRepuestoOrdenChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidRepuestoOrdenChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cantidadRepuestoOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cantidadRepuestoOrden
        {
            get
            {
                return this._cantidadRepuestoOrden;
            }
            set
            {
                this.OncantidadRepuestoOrdenChanging(value);
                this.ReportPropertyChanging("cantidadRepuestoOrden");
                this._cantidadRepuestoOrden = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cantidadRepuestoOrden");
                this.OncantidadRepuestoOrdenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cantidadRepuestoOrden;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncantidadRepuestoOrdenChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncantidadRepuestoOrdenChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fechaRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime fechaRepuesto
        {
            get
            {
                return this._fechaRepuesto;
            }
            set
            {
                this.OnfechaRepuestoChanging(value);
                this.ReportPropertyChanging("fechaRepuesto");
                this._fechaRepuesto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fechaRepuesto");
                this.OnfechaRepuestoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _fechaRepuesto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaRepuestoChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaRepuestoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad iConcurrenciaRepuestoOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> iConcurrenciaRepuestoOrden
        {
            get
            {
                return this._iConcurrenciaRepuestoOrden;
            }
            set
            {
                this.OniConcurrenciaRepuestoOrdenChanging(value);
                this.ReportPropertyChanging("iConcurrenciaRepuestoOrden");
                this._iConcurrenciaRepuestoOrden = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("iConcurrenciaRepuestoOrden");
                this.OniConcurrenciaRepuestoOrdenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _iConcurrenciaRepuestoOrden;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaRepuestoOrdenChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaRepuestoOrdenChanged();
        /// <summary>
        /// No hay ningún comentario para OrdenTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__RepuestoO__idOrd__2FCF1A8A", "OrdenTrabajo")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public OrdenTrabajo OrdenTrabajo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrdenTrabajo>("SATModel.FK__RepuestoO__idOrd__2FCF1A8A", "OrdenTrabajo").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrdenTrabajo>("SATModel.FK__RepuestoO__idOrd__2FCF1A8A", "OrdenTrabajo").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para OrdenTrabajo en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<OrdenTrabajo> OrdenTrabajoReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrdenTrabajo>("SATModel.FK__RepuestoO__idOrd__2FCF1A8A", "OrdenTrabajo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<OrdenTrabajo>("SATModel.FK__RepuestoO__idOrd__2FCF1A8A", "OrdenTrabajo", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para PrecioRepuesto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__RepuestoO__idPre__3EDC53F0", "PrecioRepuesto")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PrecioRepuesto PrecioRepuesto
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PrecioRepuesto>("SATModel.FK__RepuestoO__idPre__3EDC53F0", "PrecioRepuesto").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PrecioRepuesto>("SATModel.FK__RepuestoO__idPre__3EDC53F0", "PrecioRepuesto").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para PrecioRepuesto en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PrecioRepuesto> PrecioRepuestoReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PrecioRepuesto>("SATModel.FK__RepuestoO__idPre__3EDC53F0", "PrecioRepuesto");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PrecioRepuesto>("SATModel.FK__RepuestoO__idPre__3EDC53F0", "PrecioRepuesto", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para SATModel.Servicio en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// idServicio
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SATModel", Name="Servicio")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Servicio : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Servicio.
        /// </summary>
        /// <param name="idServicio">Valor inicial de idServicio.</param>
        /// <param name="nombreServicio">Valor inicial de nombreServicio.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Servicio CreateServicio(long idServicio, string nombreServicio)
        {
            Servicio servicio = new Servicio();
            servicio.idServicio = idServicio;
            servicio.nombreServicio = nombreServicio;
            return servicio;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad idServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idServicio
        {
            get
            {
                return this._idServicio;
            }
            set
            {
                this.OnidServicioChanging(value);
                this.ReportPropertyChanging("idServicio");
                this._idServicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idServicio");
                this.OnidServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idServicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidServicioChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidServicioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad nombreServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nombreServicio
        {
            get
            {
                return this._nombreServicio;
            }
            set
            {
                this.OnnombreServicioChanging(value);
                this.ReportPropertyChanging("nombreServicio");
                this._nombreServicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nombreServicio");
                this.OnnombreServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nombreServicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreServicioChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombreServicioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad iConcurrenciaServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> iConcurrenciaServicio
        {
            get
            {
                return this._iConcurrenciaServicio;
            }
            set
            {
                this.OniConcurrenciaServicioChanging(value);
                this.ReportPropertyChanging("iConcurrenciaServicio");
                this._iConcurrenciaServicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("iConcurrenciaServicio");
                this.OniConcurrenciaServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _iConcurrenciaServicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaServicioChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaServicioChanged();
        /// <summary>
        /// No hay ningún comentario para PrecioServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__PrecioSer__idSer__318258D2", "PrecioServicio")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PrecioServicio> PrecioServicio
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PrecioServicio>("SATModel.FK__PrecioSer__idSer__318258D2", "PrecioServicio");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PrecioServicio>("SATModel.FK__PrecioSer__idSer__318258D2", "PrecioServicio", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para SATModel.ServiciosOrden en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// idServiciosOrden
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SATModel", Name="ServiciosOrden")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ServiciosOrden : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto ServiciosOrden.
        /// </summary>
        /// <param name="idServiciosOrden">Valor inicial de idServiciosOrden.</param>
        /// <param name="cantidadServicio">Valor inicial de cantidadServicio.</param>
        /// <param name="fechaServicio">Valor inicial de fechaServicio.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ServiciosOrden CreateServiciosOrden(long idServiciosOrden, int cantidadServicio, global::System.DateTime fechaServicio)
        {
            ServiciosOrden serviciosOrden = new ServiciosOrden();
            serviciosOrden.idServiciosOrden = idServiciosOrden;
            serviciosOrden.cantidadServicio = cantidadServicio;
            serviciosOrden.fechaServicio = fechaServicio;
            return serviciosOrden;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad idServiciosOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long idServiciosOrden
        {
            get
            {
                return this._idServiciosOrden;
            }
            set
            {
                this.OnidServiciosOrdenChanging(value);
                this.ReportPropertyChanging("idServiciosOrden");
                this._idServiciosOrden = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idServiciosOrden");
                this.OnidServiciosOrdenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _idServiciosOrden;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidServiciosOrdenChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidServiciosOrdenChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cantidadServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cantidadServicio
        {
            get
            {
                return this._cantidadServicio;
            }
            set
            {
                this.OncantidadServicioChanging(value);
                this.ReportPropertyChanging("cantidadServicio");
                this._cantidadServicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cantidadServicio");
                this.OncantidadServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cantidadServicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncantidadServicioChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncantidadServicioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fechaServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime fechaServicio
        {
            get
            {
                return this._fechaServicio;
            }
            set
            {
                this.OnfechaServicioChanging(value);
                this.ReportPropertyChanging("fechaServicio");
                this._fechaServicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fechaServicio");
                this.OnfechaServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _fechaServicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaServicioChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnfechaServicioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad objServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string objServicio
        {
            get
            {
                return this._objServicio;
            }
            set
            {
                this.OnobjServicioChanging(value);
                this.ReportPropertyChanging("objServicio");
                this._objServicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("objServicio");
                this.OnobjServicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _objServicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnobjServicioChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnobjServicioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad iConcurrenciaServicioOrden en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> iConcurrenciaServicioOrden
        {
            get
            {
                return this._iConcurrenciaServicioOrden;
            }
            set
            {
                this.OniConcurrenciaServicioOrdenChanging(value);
                this.ReportPropertyChanging("iConcurrenciaServicioOrden");
                this._iConcurrenciaServicioOrden = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("iConcurrenciaServicioOrden");
                this.OniConcurrenciaServicioOrdenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _iConcurrenciaServicioOrden;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaServicioOrdenChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniConcurrenciaServicioOrdenChanged();
        /// <summary>
        /// No hay ningún comentario para OrdenTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__Servicios__idOrd__19DFD96B", "OrdenTrabajo")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public OrdenTrabajo OrdenTrabajo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrdenTrabajo>("SATModel.FK__Servicios__idOrd__19DFD96B", "OrdenTrabajo").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrdenTrabajo>("SATModel.FK__Servicios__idOrd__19DFD96B", "OrdenTrabajo").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para OrdenTrabajo en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<OrdenTrabajo> OrdenTrabajoReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrdenTrabajo>("SATModel.FK__Servicios__idOrd__19DFD96B", "OrdenTrabajo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<OrdenTrabajo>("SATModel.FK__Servicios__idOrd__19DFD96B", "OrdenTrabajo", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para PrecioServicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SATModel", "FK__Servicios__idPre__336AA144", "PrecioServicio")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PrecioServicio PrecioServicio
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PrecioServicio>("SATModel.FK__Servicios__idPre__336AA144", "PrecioServicio").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PrecioServicio>("SATModel.FK__Servicios__idPre__336AA144", "PrecioServicio").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para PrecioServicio en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PrecioServicio> PrecioServicioReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PrecioServicio>("SATModel.FK__Servicios__idPre__336AA144", "PrecioServicio");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PrecioServicio>("SATModel.FK__Servicios__idPre__336AA144", "PrecioServicio", value);
                }
            }
        }
    }
}
