Imports MySql.Data.MySqlClient
Module Modulo_Conexion
    Friend Conexion As New MySqlConnection
    Friend SC As New MySqlCommand
    Friend DA As New MySqlDataAdapter
    Friend DS As New DataSet()
    Friend DT As New DataTable
    Friend SC2 As New MySqlCommand
    Friend DA2 As New MySqlDataAdapter
    Friend DS2 As New DataSet()
    Friend DT2 As New DataTable
    Friend SC3 As New MySqlCommand
    Friend DA3 As New MySqlDataAdapter
    Friend DS3 As New DataSet()
    Friend DT3 As New DataTable
    Friend SC4 As New MySqlCommand
    Friend DA4 As New MySqlDataAdapter
    Friend DS4 As New DataSet()
    Friend DT4 As New DataTable
    Friend SC5 As New MySqlCommand
    Friend DA5 As New MySqlDataAdapter
    Friend DS5 As New DataSet()
    Friend DT5 As New DataTable
    Friend SC6 As New MySqlCommand
    Friend DA6 As New MySqlDataAdapter
    Friend DS6 As New DataSet()
    Friend DT6 As New DataTable
    Friend SC7 As New MySqlCommand
    Friend DA7 As New MySqlDataAdapter
    Friend DS7 As New DataSet()
    Friend DT7 As New DataTable
    Friend SC8 As New MySqlCommand
    Friend DA8 As New MySqlDataAdapter
    Friend DS8 As New DataSet()
    Friend DT8 As New DataTable
    Friend SC9 As New MySqlCommand
    Friend DA9 As New MySqlDataAdapter
    Friend DS9 As New DataSet()
    Friend DT9 As New DataTable
    Friend SC0 As New MySqlCommand
    Friend DA0 As New MySqlDataAdapter
    Friend DS0 As New DataSet()
    Friend DT0 As New DataTable
    Friend SC10 As New MySqlCommand
    Friend DA10 As New MySqlDataAdapter
    Friend DS10 As New DataSet()
    Friend DT10 As New DataTable
    Friend SC11 As New MySqlCommand
    Friend DA11 As New MySqlDataAdapter
    Friend DS11 As New DataSet()
    Friend DT11 As New DataTable
    Friend SC12 As New MySqlCommand
    Friend DA12 As New MySqlDataAdapter
    Friend DS12 As New DataSet()
    Friend DT12 As New DataTable
    Friend SC13 As New MySqlCommand
    Friend DA13 As New MySqlDataAdapter
    Friend DS13 As New DataSet()
    Friend DT13 As New DataTable
    Friend SC14 As New MySqlCommand
    Friend DA14 As New MySqlDataAdapter
    Friend DS14 As New DataSet()
    Friend DT14 As New DataTable
    Friend SC15 As New MySqlCommand
    Friend DA15 As New MySqlDataAdapter
    Friend DS15 As New DataSet()
    Friend DT15 As New DataTable
    Friend SC16 As New MySqlCommand
    Friend DA16 As New MySqlDataAdapter
    Friend DS16 As New DataSet()
    Friend DT16 As New DataTable
    Friend SC17 As New MySqlCommand
    Friend DA17 As New MySqlDataAdapter
    Friend DS17 As New DataSet()
    Friend DT17 As New DataTable
    Friend SC18 As New MySqlCommand
    Friend DA18 As New MySqlDataAdapter
    Friend DS18 As New DataSet()
    Friend DT18 As New DataTable
    Friend SC19 As New MySqlCommand
    Friend DA19 As New MySqlDataAdapter
    Friend DS19 As New DataSet()
    Friend DT19 As New DataTable
    Friend SC20 As New MySqlCommand
    Friend DA20 As New MySqlDataAdapter
    Friend DS20 As New DataSet()
    Friend DT20 As New DataTable
    Friend SC21 As New MySqlCommand
    Friend DA21 As New MySqlDataAdapter
    Friend DS21 As New DataSet()
    Friend DT21 As New DataTable
    Friend SC22 As New MySqlCommand
    Friend DA22 As New MySqlDataAdapter
    Friend DS22 As New DataSet()
    Friend DT22 As New DataTable
End Module
